name: First Workflow 

on: 
  push: 
    branches: 
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display a message
        run: echo "Hello, Github Actions!"

      - name: cat swapi.html
        run: cat swapi.html